export const POST_LIST_REQUEST = 'FETCH_POSTS_REQUEST';
export const POST_LIST_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const POST_LIST_FAIL = 'FETCH_POSTS_FAIL';

export const POST_DETAILS_REQUEST = 'FETCH_POST_REQUEST';
export const POST_DETAILS_SUCCESS = 'FETCH_POST_SUCCESS';
export const POST_DETAILS_FAIL = 'FETCH_POST_FAIL';