export const POST_LIST_REQUEST = 'FETCH_POSTS_REQUEST';
export const POST_LIST_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const POST_LIST_FAIL = 'FETCH_POSTS_FAIL';

export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST';
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS';
export const POST_DETAILS_FAIL = 'POST_DETAILS_FAIL';

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL';
export const POST_CREATE_RESET = 'POST_CREATE_RESET';

export const POST_CREATE_COMMENT_REQUEST = 'POST_CREATE_COMMENT_REQUEST';
export const POST_CREATE_COMMENT_SUCCESS = 'POST_CREATE_COMMENT_SUCCESS';
export const POST_CREATE_COMMENT_FAIL = 'POST_CREATE_COMMENT_FAIL';
export const POST_CREATE_COMMENT_RESET = 'POST_CREATE_COMMENT_RESET';