export const POST_LIST_REQUEST = 'FETCH_POSTS_REQUEST';
export const POST_LIST_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const POST_LIST_FAIL = 'FETCH_POSTS_FAIL';

export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST';
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS';
export const POST_DETAILS_FAIL = 'POST_DETAILS_FAIL';